name: gu-psyc-347-jb
channels:
  - default
  - conda-forge
  - eoas_ubc
dependencies:
  - python=3.7.*
  - sphinx=2.4.4
  - pip
  - runjb
  - git
  - pandas
  - scipy
  - numpy
  - matplotlib
  - pip:
    - jupyter-book>=0.7.0b