# Book settings
title: Computational Models of Human Social Behavior
author: Shawn A. Rhoads
copyright: '2020'
logo: '_images/logo.png'

# Main page settings
footer_text: Created by <a href="http://shawnrhoads.github.io/">Shawn A Rhoads</a> using <a href="https://jupyterbook.org/">Jupyter Book</a>.

repository:
  url: https://github.com/shawnrhoads/gu-psyc-347
  branch: "jupyter-book-spring-2021"
  path_to-book: "docs"


html:
  use_repository_button: true
  use_issues_button: true
  google_analytics_id: ""

launch_buttons:
  colab_url: https://colab.research.google.com

latex:
  latex_documents:
    targetname: book.tex
