name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - master
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    # paths:
    # - docs/**

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: gu-psyc-347-jb
        environment-file: environment.yml
        python-version: 3.7
        auto-activate-base: false
        miniconda-version: 'latest'

    - name: Build Book
      run: |
        conda info
        conda activate gu-psyc-347-jb
        runjb docs

    # - name: Install jupyter_book
    #     shell: bash -l {0}
    #     run:  pip install jupyter-book

    # # Install dependencies
    # - name: Set up Python 3.7
    #   uses: actions/setup-python@v1
    #   with:
    #     python-version: 3.7

    # - name: Install dependencies
    #   run: |
    #     pip install -r requirements.txt

    # # Build the page
    # - name: Build the book
    #   run: |
    #     jupyter-book build ./docs

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        publish_branch: gh-pages